name: CI Java Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
    - name: Configurar JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Compilar y ejecutar tests
      run: mvn clean verify
    - name: Verificar existencia de reporte JaCoCo
      run: if [ -d "target/site/jacoco/" ]; then echo "JaCoCo report exists"; else echo "JaCoCo report missing"; exit 1; fi
    - name: Subir reporte de JaCoCo
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: target/site/jacoco/
